---
- name: Update SSL certificate on Proxmox
  hosts: all
  become: true
  become_user: exadmn
  become_method: sudo
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    certificate_path: "/var/lib/awx/projects/ssl-exaservers.com/certificate.crt"
    private_key_path: "/var/lib/awx/projects/ssl-exaservers.com/privatekey.key"
    ca_bundle_path: "/var/lib/awx/projects/ssl-exaservers.com/ca_bundle.crt"

  tasks:
    - name: Remove exisiting files
      become: true
      become_user: root
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/pve/local/pveproxy-ssl.key
        - /etc/pve/local/pveproxy-ssl.pem

    - name: Copy SSL private key
      copy:
        src: "{{ private_key_path }}"
        dest: "/tmp/pveproxy-ssl.key"

    - name: Copy SSL certificate
      copy:
        src: "{{ certificate_path }}"
        dest: "/tmp/exaservers.crt"

    - name: Copy SSL ca bundle
      copy:
        src: "{{ ca_bundle_path }}"
        dest: "/tmp/ca_bundle.crt"

    - name: Copy certificate.crt content
      slurp:
        src: /tmp/exaservers.crt
      register: cert_contents

    - name: Copy ca_bundle content
      slurp:
        src: /tmp/ca_bundle.crt
      register: bundle_contents

    - name: Combine contents into pve-ssl file
      template:
        src: pveproxy-ssl.j2
        dest: /tmp/pveproxy-ssl.pem
      vars:
        certificate_content: "{{ cert_contents['content'] | b64decode }}"
        bundle_content: "{{ bundle_contents['content'] | b64decode }}"

    - name: sudo move files
      become: true
      become_user: root
      command:
        cmd: "cp {{ item }} /etc/pve/local/"
      loop:
        - /tmp/pveproxy-ssl.key
        - /tmp/pveproxy-ssl.pem

    - name: Restart pveproxy service
      become: true
      become_user: root
      service:
        name: pveproxy
        state: restarted
