---
- name: Update SSL certificate on Proxmox
  hosts: all
  become: true
  become_user: exadmn
  become_method: sudo
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    certificate_path: "/var/lib/awx/projects/ssl-exaservers.com/certificate.crt"
    private_key_path: "/var/lib/awx/projects/ssl-exaservers.com/privatekey.key"
    ca_bundle_path: "/var/lib/awx/projects/ssl-exaservers.com/ca_bundle.crt"

  tasks:
    - name: Remove exisiting files
      become: true
      become_user: root
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/pve/nodes/{{ ansible_hostname }}/pve-ssl.key
        - /etc/pve/nodes/{{ ansible_hostname }}/pve-ssl.pem

    - name: Copy SSL private key to remote srv
      become: true
      become_user: root
      copy:
        src: "{{ private_key_path }}"
        dest: "/root/pve-ssl.key"

    - name: Copy SSL private key to /etc/pve/nodes/
      become: true
      become_user: root
      copy:
        src: "/root/pve-ssl.key"
        dest: "/etc/pve/nodes/lnx-pve05/pve-ssl.key"
        remote_src: true

    - name: Copy SSL certificate
      copy:
        src: "{{ certifcate_path }}"
        dest: "/root/exaservers.crt"

    - name: Copy SSL ca bundle
      copy:
        src: "{{ ca_bundle_path }}"
        dest: "/root/ca_bundle.crt"

    - name: Copy certificate.crt content
      slurp:
        src: /root/exaservers.crt
      register: cert_contents

    - name: Copy ca_bundle content
      slurp:
        src: /root/ca_bundle.crt
      register: bundle_contents

    - name: Combine contents into pve-ssl file
      become: true
      become_user: root
      template:
        src: pve-ssl.j2
        dest: /etc/pve/nodes/{{ ansible_hostname }}/pve-ssl.pem
      vars:
        certificate_content: "{{ cert_contents['content'] | b64decode }}"
        bundle_content: "{{ bundle_contents['content'] | b64decode }}"

    - name: Restart pveproxy service
      service:
        name: pveproxy
        state: restarted
